// <auto-generated />
using System;
using HangfireExample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HangfireExample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211116131725_AddedLogs")]
    partial class AddedLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HangfireExample.Models.Processing.ProcessingQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessingQueueStatus")
                        .HasColumnType("int");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProcessingQueue");
                });

            modelBuilder.Entity("HangfireExample.Models.Processing.ProcessingQueueLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingQueueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingQueueId");

                    b.ToTable("ProcessingQueueLog");
                });

            modelBuilder.Entity("HangfireExample.Models.Processing.ProcessingQueueLog", b =>
                {
                    b.HasOne("HangfireExample.Models.Processing.ProcessingQueue", "ProcessingQueue")
                        .WithMany("ProcessingQueueLogs")
                        .HasForeignKey("ProcessingQueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingQueue");
                });

            modelBuilder.Entity("HangfireExample.Models.Processing.ProcessingQueue", b =>
                {
                    b.Navigation("ProcessingQueueLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
